#include<stdio.h>
#include<stdlib.h>
#include<string.h>
#include<sys/types.h>
#include<sys/stat.h>
#include<sys/wait.h>
#include<sys/msg.h>
#include<sys/ipc.h>
#include<unistd.h>
#include<signal.h>
#include<utime.h>
#include<dirent.h>
#include<fcntl.h>
